import { TableExportConfig } from './exportXLSX'

export const MATERNIDADE_EXPORT_CONFIG: TableExportConfig = {
  tableName: 'registros_maternidade',
  sheetName: 'Maternidade',
  columns: [
    { source: 'data', header: 'Data', format: 'date' },
    { source: 'pasto', header: 'Pasto' },
    { source: 'lote', header: 'Lote' },
    { source: 'peso_cria_kg', header: 'Peso Cria (kg)', format: 'number' },
    { source: 'id_provisorio_cria', header: 'ID Provisório' },
    { source: 'tratamento', header: 'Tratamentos' },
    { source: 'tipo_parto', header: 'Tipo de Parto', transform: (value) => Array.isArray(value) ? value.join(', ') : value },
    { source: 'sexo', header: 'Sexo' },
    { source: 'raca', header: 'Raça' },
    { source: 'categoria_mae', header: 'Categoria da Mãe' },
    { source: 'escore_matriz', header: 'Escore Matriz', format: 'number' },
    { source: 'id_chip_mae', header: 'Chip Mãe' },
    { source: 'id_brinco_cria', header: 'Brinco Cria' },
    { source: 'id_chip_cria', header: 'Chip Cria' },
    { source: 'id_brinco_mae', header: 'Brinco Mãe' },
    { source: 'docilidade_matriz', header: 'Docilidade Matriz' },
    { source: 'observacao_parto', header: 'Observações' }
  ]
}

export const PASTAGENS_EXPORT_CONFIG: TableExportConfig = {
  tableName: 'registros_pastagens',
  sheetName: 'Pastagens',
  columns: [
    { source: 'data', header: 'Data', format: 'date' },
    { source: 'manejador', header: 'Manejador' },
    { source: 'lote', header: 'Lote' },
    { source: 'pasto_saida', header: 'Pasto Saída' },
    { source: 'avaliacao_saida', header: 'Avaliação Saída', format: 'number' },
    { source: 'pasto_entrada', header: 'Pasto Entrada' },
    { source: 'avaliacao_entrada', header: 'Avaliação Entrada', format: 'number' },
    { source: 'vaca', header: 'Vaca', format: 'number' },
    { source: 'touro', header: 'Touro', format: 'number' },
    { source: 'bezerro', header: 'Bezerro', format: 'number' },
    { source: 'boi_magro', header: 'Boi Magro', format: 'number' },
    { source: 'garrote', header: 'Garrote', format: 'number' },
    { source: 'novilha', header: 'Novilha', format: 'number' },
    { source: 'total_animais', header: 'Total Animais', format: 'number' },
    { source: 'escore_gado', header: 'Escore Gado', format: 'number' },
    { source: 'escore_fezes', header: 'Escore Fezes', format: 'number' },
    { source: 'numero_pessoas_manejo', header: 'Nº Pessoas Manejo', format: 'number' },
    { source: 'pasto_saida_area_util', header: 'Pasto Saída Área Útil' },
    { source: 'pasto_saida_especie', header: 'Pasto Saída Espécie' },
    { source: 'pasto_entrada_area_util', header: 'Pasto Entrada Área Útil' },
    { source: 'pasto_entrada_especie', header: 'Pasto Entrada Espécie' },
    { source: 'gado_contado', header: 'Gado Contado' },
    { source: 'avaliacao_geral', header: 'Animal Morto', transform: (value) => value?.animalMorto?.valor || '' },
    { source: 'avaliacao_geral', header: 'Animal Morto Obs', transform: (value) => value?.animalMorto?.observacao || '' },
    { source: 'avaliacao_geral', header: 'Bebedouros/Cochos', transform: (value) => value?.bebedourosCochos?.valor || '' },
    { source: 'avaliacao_geral', header: 'Bebedouros/Cochos Obs', transform: (value) => value?.bebedourosCochos?.observacao || '' },
    { source: 'avaliacao_geral', header: 'Carrapatos/Moscas', transform: (value) => value?.carrapatosMoscas?.valor || '' },
    { source: 'avaliacao_geral', header: 'Carrapatos/Moscas Obs', transform: (value) => value?.carrapatosMoscas?.observacao || '' },
    { source: 'avaliacao_geral', header: 'Animais Entreverados', transform: (value) => value?.animaisEntreverados?.valor || '' },
    { source: 'avaliacao_geral', header: 'Animais Entreverados Obs', transform: (value) => value?.animaisEntreverados?.observacao || '' },
    { source: 'avaliacao_geral', header: 'Pastagens Taxa Lotação Adequada', transform: (value) => value?.pastagensTaxaLotacao?.valor || '' },
    { source: 'avaliacao_geral', header: 'Pastagens Taxa Lotação Adequada Obs', transform: (value) => value?.pastagensTaxaLotacao?.observacao || '' },
    { source: 'avaliacao_geral', header: 'Cercas/Cochos/Porteiras', transform: (value) => value?.cercasCochosPorteiras?.valor || '' },
    { source: 'avaliacao_geral', header: 'Cercas/Cochos/Porteiras Obs', transform: (value) => value?.cercasCochosPorteiras?.observacao || '' },
    { source: 'avaliacao_geral', header: 'Animais Machucados/Doentes', transform: (value) => value?.animaisMachucadosDoentesBichados?.valor || '' },
    { source: 'avaliacao_geral', header: 'Animais Machucados/Doentes Obs', transform: (value) => value?.animaisMachucadosDoentesBichados?.observacao || '' },
    { source: 'equipe_nomes', header: 'Equipe Nomes', transform: (value) => Array.isArray(value) ? value.join(', ') : value }
  ]
}

export const RODEIO_EXPORT_CONFIG: TableExportConfig = {
  tableName: 'registros_rodeio',
  sheetName: 'Rodeio',
  columns: [
    { source: 'data', header: 'Data', format: 'date' },
    { source: 'pasto', header: 'Pasto' },
    { source: 'lote', header: 'Lote' },
    { source: 'vaca', header: 'Vaca', format: 'number' },
    { source: 'touro', header: 'Touro', format: 'number' },
    { source: 'bezerro', header: 'Bezerro', format: 'number' },
    { source: 'boi', header: 'Boi', format: 'number' },
    { source: 'garrote', header: 'Garrote', format: 'number' },
    { source: 'novilha', header: 'Novilha', format: 'number' },
    { source: 'total_cabecas', header: 'Total Cabeças', format: 'number' },
    { source: 'escore_gado', header: 'Escore Gado', format: 'number' },
    { source: 'escore_fezes', header: 'Escore Fezes', format: 'number' },
    { source: 'equipe', header: 'Equipe (nº pessoas)', format: 'number' },
    { source: 'gado_contado', header: 'Gado Contado' },
    { source: 'diagnosticos', header: 'Animal Morto', transform: (value) => value?.animalMorto?.valor || '' },
    { source: 'diagnosticos', header: 'Animal Morto Obs', transform: (value) => value?.animalMorto?.observacao || '' },
    { source: 'diagnosticos', header: 'Bebedouros/Cochos', transform: (value) => value?.bebedourosCochos?.valor || '' },
    { source: 'diagnosticos', header: 'Bebedouros/Cochos Obs', transform: (value) => value?.bebedourosCochos?.observacao || '' },
    { source: 'diagnosticos', header: 'Carrapatos/Moscas', transform: (value) => value?.carrapatosMoscas?.valor || '' },
    { source: 'diagnosticos', header: 'Carrapatos/Moscas Obs', transform: (value) => value?.carrapatosMoscas?.observacao || '' },
    { source: 'diagnosticos', header: 'Animais Entreverados', transform: (value) => value?.animaisEntreverados?.valor || '' },
    { source: 'diagnosticos', header: 'Animais Entreverados Obs', transform: (value) => value?.animaisEntreverados?.observacao || '' },
    { source: 'diagnosticos', header: 'Pastagens Taxa Lotação Adequada', transform: (value) => value?.pastagensTaxaLotacao?.valor || '' },
    { source: 'diagnosticos', header: 'Pastagens Taxa Lotação Adequada Obs', transform: (value) => value?.pastagensTaxaLotacao?.observacao || '' },
    { source: 'diagnosticos', header: 'Cercas/Cochos/Porteiras', transform: (value) => value?.cercasCochosPorteiras?.valor || '' },
    { source: 'diagnosticos', header: 'Cercas/Cochos/Porteiras Obs', transform: (value) => value?.cercasCochosPorteiras?.observacao || '' },
    { source: 'diagnosticos', header: 'Animais Machucados/Doentes', transform: (value) => value?.animaisMachucadosDoentesBichados?.valor || '' },
    { source: 'diagnosticos', header: 'Animais Machucados/Doentes Obs', transform: (value) => value?.animaisMachucadosDoentesBichados?.observacao || '' },
    { source: 'equipe_nomes', header: 'Equipe Nomes', transform: (value) => Array.isArray(value) ? value.join(', ') : value }
  ]
}
