-- Habilitar RLS nas tabelas que têm políticas criadas
ALTER TABLE public.pastos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.frigorificos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bebedouros ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.causas_morte ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mineral ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.insumos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proteinado ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dietas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.racao ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fazendas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fornecedores ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.funcionarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.usuarios ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.peoes ENABLE ROW LEVEL SECURITY;;
